// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC28Yc5GGBiLR9bK4EemI-Zsb9XlP6HrKI',
    appId: '1:924485303152:web:e0b3b2a307d6420ed9adb5',
    messagingSenderId: '924485303152',
    projectId: 'mychatapp-b78a5',
    authDomain: 'mychatapp-b78a5.firebaseapp.com',
    storageBucket: 'mychatapp-b78a5.appspot.com',
    measurementId: 'G-FCS136RQ7V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFK0Kg2gM9cM_yB2segz7CGJCVkd2zRaw',
    appId: '1:924485303152:android:85979118b5378b67d9adb5',
    messagingSenderId: '924485303152',
    projectId: 'mychatapp-b78a5',
    storageBucket: 'mychatapp-b78a5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBi5llL5TxLigrHwDsN03Sz-M6QQe85E7w',
    appId: '1:924485303152:ios:1a979f1f4b7299fcd9adb5',
    messagingSenderId: '924485303152',
    projectId: 'mychatapp-b78a5',
    storageBucket: 'mychatapp-b78a5.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBi5llL5TxLigrHwDsN03Sz-M6QQe85E7w',
    appId: '1:924485303152:ios:b79da044aeb94af3d9adb5',
    messagingSenderId: '924485303152',
    projectId: 'mychatapp-b78a5',
    storageBucket: 'mychatapp-b78a5.appspot.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );
}
